POST https://gymguardianapi.onrender.com/workouts
Content-type: application/json


###

GET https://gymguardianapi.onrender.com/workouts?search=

###

PUT https://gymguardianapi.onrender.com/workouts/229a3421-a00d-48e9-af39-5844007caca9
Content-type: application/json

{
  "title": "Video Node",
  "description": "Esse é o 2º vídeo",
  "duration": 155
}

###

DELETE https://gymguardianapi.onrender.com/workouts/229a3421-a00d-48e9-af39-5844007caca9